### ISSUE TITLE
dropdb fails silently if database is open in pgAdmin3

### ISSUE THREAD

**Issue by proehlen** [olalonde/pgtools#14] opened 2017-01-06 16:55 UTC
dropdb errors are working for me generally - ie the following code will reach the console.error line if the database doesn't already exist:
```
pgtools
    .dropdb(config, testDbName)
    .catch((error)=>{
      console.log(error);
    })
```

However if I happen to have the database open in pgAdmin3 it won't drop the database and it won't throw an error.

**Comment by gerpedrosa** [comment] 2017-06-07 10:24
If the database has active connections postgres throws an error trying to drop the database and this module crash.
The problem is that error code "55006" is not in the error list, so in PgError function errors[pgErr.code] is undefined and the code crash getting message and name of undefined.

**Comment by olalonde** [comment] 2017-06-07 20:18
Oops, anyone wants to send a PR?

**Comment by gerpedrosa** [comment] 2017-06-08 07:34
I was using version 0.2.3, it's already fixed in the master branch

**Comment by proehlen** [comment] 2017-06-08 08:11
I just re-tested it with 0.2.3 and it's no longer failing silently for me but it's not reaching the callback function with an error either.  The node process is terminating with this:
```
> pgtools-dropdb@1.0.0 start /home/peter/Temp/pgtools-dropdb
> node index.js

/home/peter/Temp/pgtools-dropdb/node_modules/pgtools/index.js:22
  var message = (errors[pgErr.code].message || 'Unknown Postgres error.') + ' Cause: ' + pgErr.message;
                                   ^

TypeError: Cannot read property 'message' of undefined
    at PgError (/home/peter/Temp/pgtools-dropdb/node_modules/pgtools/index.js:22:36)
    at Query.callback (/home/peter/Temp/pgtools-dropdb/node_modules/pgtools/index.js:60:17)
    at Query.handleError (/home/peter/Temp/pgtools-dropdb/node_modules/pg/lib/query.js:141:17)
    at Connection.<anonymous> (/home/peter/Temp/pgtools-dropdb/node_modules/pg/lib/client.js:181:26)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/home/peter/Temp/pgtools-dropdb/node_modules/pg/lib/connection.js:136:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pgtools-dropdb@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pgtools-dropdb@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/peter/.npm/_logs/2017-06-08T08_08_43_253Z-debug.log
```

There's a repro of sorts here: https://github.com/proehlen/repro-pgtools-issue-14

By the way, I can't even remember what project I was working on that prompted me to raise this issue so I have no stake in the issue any more.  Feel free to close it.

**Comment by proehlen** [comment] 2017-06-08 08:13
In case it's relevant to the above, I'm using this version of postgresql:
```
postgres --version
postgres (PostgreSQL) 9.6.3
```

**Comment by adriaandotcom** [comment] 2021-03-20 06:06
I want to start with a clean slate. So closing this issue as it's from 2017. Please reopen any issue if it's still a problem at the moment.

**Closed as completed by adriaandotcom** 2021-03-20 06:06 UTC
